name: Generate Snake SVGs

on:
  push:
  schedule:
    - cron: "0 0 * * *" # Runs daily

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: platane/snk@v3
        with:
          github_user_name: sneh2102
          outputs: |
            output/snake.svg?palette=github-dark
            output/snake-light.svg?palette=github-light
      - name: Commit SVGs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/snake.svg output/snake-light.svg
          git commit -m "Update snake SVGs" || echo "No changes to commit"
          git push
