name: Generate Snake SVGs

on:
  schedule: # Execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main # Changed from 'master' to 'main' to match your current branch

jobs:
  generate:
    permissions:
      contents: write # Ensure the workflow has write permissions
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light

      - name: Push SVGs to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
